[project]
name = "callthread"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "azure-ai-projects>=2.0.0",
    "azure-identity>=1.25.3",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
callthread = "callthread:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
